### PR TITLE
add .DS_Store to .gitignore

### PR DESCRIPTION
**Pull request by DarhkVoyd**
**What kind of change does this PR introduce?**
This PR aims to update `.gitignore` to avoid adding unnecessary MacOS Finder configuration `.DS_Store` to the repository.

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by Relequestual** [comment]
If we're going to ignore OS specific things (which we should), it may be best to add a larger list to the .gitignore file rather than just one part.
See https://www.toptal.com/developers/gitignore/api/macos,windows

**Review by DhairyaMajmudar — COMMENTED** [review]
Does this file also includes files to be removed from various linux destros ?

**Comment by DarhkVoyd** [comment]
> Does this file also includes files to be removed from various linux destros ?

I am not sure what files are to be excluded for linux.

**Review by benjagm — APPROVED** [review]
Thanks. LGTM

**Comment by benjagm** [comment]
Can you please resolve the conflicts?

**Review by Relequestual — APPROVED** [review]

**Pull request merged**
