### PR TITLE
update to latest landscape structure for tooling workflow

### PR DESCRIPTION
**Pull request by DarhkVoyd**
**What kind of change does this PR introduce?**
The current landscape.yml is following an outdated structure with nullish keys, which is an interruption for landscape's tooling automation workflow. This PR aims to update landscape.yml to follow the latest structure which is cleaner and update the landscape2 version that supports it.

**Issue Number:**

-  Closes #___ 
-  Related to #___ 
-  Others? 

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

### CODE REVIEW

**Comment by DarhkVoyd** [comment]
The build workflow fails as this the older landscape tool version expects the root key to be "landscape", updating the "landscape2" to the latest version fixes this which is included in the PR.

**Review by benjagm — APPROVED** [review]
It is great that you fixed this. Thanks DV!

**Comment by benjagm** [comment]
Hi DV. The CI/CD workflow failed here: https://github.com/json-schema-org/landscape/actions/runs/10092190239

Can you please check it?

**Comment by DarhkVoyd** [comment]
> The build workflow fails as this the older landscape tool version expects the root field to be "landscape", updating the "landscape2" to the latest version fixes this which is included in the PR.

Yeah, as I mentioned earlier the CI/CD workflow is failing because of the above reason, this PR also updates the landscape version from 0.9 to 0.10, that will fix the build error.

**Comment by benjagm** [comment]
> > The build workflow fails as this the older landscape tool version expects the root field to be "landscape", updating the "landscape2" to the latest version fixes this which is included in the PR.
> 
> Yeah, as I mentioned earlier the CI/CD workflow is failing because of the above reason, this PR also updates the landscape version from 0.9 to 0.10, that will fix the build error.

Thanks DV. I was just double-checking. PR Merged.

**Pull request merged**
